covid_dashboard/covid_dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

covid_dashboard/dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('map_data/', views.get_map_data, name='get_map_data'),
    path('covid_data/', views.get_covid_data, name='get_covid_data'),
    path('summary_data/', views.get_summary_data, name='get_summary_data'),
    path('vaccination_data/', views.get_vaccinated_percentage,
         name='get_vaccinated_percentage'),
    path('weekly_max_data/', views.get_weekly_maxs, name='get_weekly_maxs'),
    path('new_vaccinated_data/', views.get_new_vaccinated_data,
         name='get_new_vaccinated_data'),
    path('new_deaths_data/', views.get_new_deaths_data,
         name='get_new_deaths_data'),
    path('last_update/', views.get_last_update, name='get_last_update'),
]

covid_dashboard/dashboard/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from clickhouse_driver import Client


def get_db_conn():
    return Client("covid-database")


def index(request):
    return render(request, "index.html")


def get_map_data(request):
    results = get_db_conn().execute("""
        SELECT
            Location,
            CEIL(AVG(NewCasesPerMil) / 10) AS NewCases,
            CEIL(AVG(NewDeathsPerMil) / 10) AS NewDeaths,
            CEIL(AVG(NewVaccinationsSmoothPerMil) / 10) AS NewVaccinations,
            ROUND(MAX(Population / 1000000), 1) AS PopulationMillion
        FROM covid19.updates
        WHERE
            Continent='Africa' AND UpdateDate>=today() - 7
        GROUP BY
            Location
        ORDER BY Location DESC;
    """)
    return JsonResponse(results, safe=False,
                        json_dumps_params={"default": str})


def get_covid_data(request):
    results = get_db_conn().execute("""
        SELECT
            Location,
            toStartOfWeek(UpdateDate) AS Week,
            CEIL(AVG(NewCasesPerMil)/ 10) AS NewCasesPer100K
        FROM covid19.updates
        WHERE Continent='Africa'
        GROUP BY
            Location,
            Week
        ORDER BY Week ASC;
    """)
    return JsonResponse(results, safe=False,
                        json_dumps_params={"default": str})


def get_summary_data(request):
    results = get_db_conn().execute("""
        SELECT
            Location,
            CEIL(MAX(Population) / 100000) AS PopulationPer100kQuotient,
            MAX(TotalCases) AS TotalCases,
            CEIL(TotalCases / PopulationPer100kQuotient) AS CasesPer100k,
            CEIL(AVG(NewCasesPerMil) / 10) AS NewCases,
            MAX(TotalDeaths) AS TotalDeaths,
            CEIL(TotalDeaths / PopulationPer100kQuotient) AS DeathsPer100k,
            CEIL(AVG(NewDeathsPerMil) / 10) AS NewDeaths,
            MAX(TotalVaccinations) AS TotalVaccinations,
            CEIL(TotalVaccinations / PopulationPer100kQuotient) AS VaccPer100k,
            CEIL(AVG(NewVaccinationsSmoothPerMil) / 10) AS NewVaccinations
        FROM covid19.updates
        WHERE
            Continent='Africa' AND UpdateDate>=today() - 7
        GROUP BY
            Location
        ORDER BY Location DESC;
    """)
    return JsonResponse(results, safe=False,
                        json_dumps_params={"default": str})


def get_vaccinated_percentage(request):
    results = get_db_conn().execute("""
        SELECT
            Location,
            MAX(PeopleVaccinated) AS FirstVaccine,
            MAX(PeopleFullyVaccinated) AS FullyVaccinated,
            MAX(TotalBoosters) AS BoosterVaccine,
            MAX(Population) AS Population,
            CEIL(FirstVaccine / Population * 100) AS PercentOneDose,
            CEIL(FullyVaccinated / Population * 100) AS PercentTwoDose,
            CEIL(BoosterVaccine / Population * 100) AS PercentThreeDose
        FROM covid19.updates
        WHERE Continent='Africa'
        GROUP BY
            Location
        ORDER BY Location ASC;
    """)
    return JsonResponse(results, safe=False,
                        json_dumps_params={"default": str})


def get_weekly_maxs(request):
    cases_results = get_db_conn().execute("""
        (SELECT TOP 5
            Location,
            CEIL(AVG(NewCasesPerMil) / 10) AS newCases
        FROM covid19.updates
        WHERE Continent='Africa' AND UpdateDate>=today() - 7
        GROUP BY Location
        ORDER BY newCases DESC)
    """)

    deaths_results = get_db_conn().execute("""
        SELECT TOP 5
            Location,
            CEIL(AVG(NewDeathsPerMil) / 10) AS newDeaths
        FROM covid19.updates
        WHERE Continent='Africa' AND UpdateDate>=today() - 7
        GROUP BY Location
        ORDER BY newDeaths DESC
    """)

    vacc_results = get_db_conn().execute("""
        SELECT TOP 5
            Location,
            CEIL(AVG(NewVaccinationsSmoothPerMil) / 10) AS newVacc
        FROM covid19.updates
        WHERE Continent='Africa' AND UpdateDate>=today() - 7
        GROUP BY Location
        ORDER BY newVacc DESC
    """)
    results = [cases_results, deaths_results, vacc_results]
    return JsonResponse(results, safe=False,
                        json_dumps_params={"default": str})


def get_new_vaccinated_data(request):
    results = get_db_conn().execute("""
        SELECT
            Location,
            toStartOfWeek(UpdateDate) AS Week,
            CEIL(SUM(NewVaccinationsSmoothPerMil)/ 10)
            AS NewVaccinationsPer100k,
            ceil(AVG(NewVaccinationsSmoothPerMil) / 10)
            AS AvgNewVaccinationsPer100k
        FROM covid19.updates
        WHERE Continent='Africa'
        GROUP BY
            Location,
            Week
        ORDER BY Week ASC;
    """)
    return JsonResponse(results, safe=False,
                        json_dumps_params={"default": str})


def get_new_deaths_data(request):
    results = get_db_conn().execute("""
        SELECT
            Location,
            toStartOfWeek(UpdateDate) AS Week,
            CEIL(SUM(NewDeathsPerMil)/ 10)
            AS NewDeathsPer100k,
            CEIL(AVG(NewDeathsPerMil) / 10)
            AS AvgNewDeathsPer100k
        FROM covid19.updates
        WHERE Continent='Africa'
        GROUP BY
            Location,
            Week
        ORDER BY Week ASC;
    """)
    return JsonResponse(results, safe=False,
                        json_dumps_params={"default": str})


def get_last_update(request):
    results = get_db_conn().execute(
        "SELECT MAX(UpdateDate) FROM covid19.updates"
    )
    return HttpResponse(results[0])

covid_dashboard/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="author" content="Walt Adamson" />
    <meta name="description" content="Visualisations of COVID-19 statistics across Africa" />

    <title>
        {% block title_block %}
            Africa Tracker
        {% endblock %}
    </title>

    <!-- scale web-page to client device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-KSNRX24');</script>
    <!-- End Google Tag Manager -->

    <!-- Open Graph protocol integration -->
    <meta property="og:title" content="COVID-19 Africa Tracker" />
    <meta property="og:image" content="{% static 'assets/splash.webp' %}" />
    <meta property="og:type" content="website" />

    <link rel="icon" href="{% static 'favicon.ico' %}" />
    <link rel="icon" href="{% static 'favicon.svg' %}" type="image/svg+xml" />

    <!-- load stylesheets -->
    <link rel="stylesheet" href="{% static 'style/nav.css' %}" />
    <link rel="stylesheet" href="{% static 'style/global.css' %}" />
    <link rel="stylesheet" href="{% static 'style/index.css' %}" />
    <link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/dataTables.bootstrap5.min.css' %}">

    <!-- load fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" crossorigin />

    <!-- load scripts -->
    <script src="{% static 'javascript/plotly.js' %}"></script>
    <script src="{% static 'javascript/highcharts.js' %}"></script>
    <script src="{% static 'javascript/highcharts-no-data-to-display.js' %}"></script>
    <script src="{% static 'javascript/highcharts-more.js' %}"></script>
    <script src="{% static 'javascript/highcharts-maps-modules.js' %}"></script>
    <script src="{% static 'javascript/highcharts-africa.js' %}"></script>
    <script src="{% static 'javascript/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'javascript/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'javascript/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.bootstrap5.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/index.js' %}"></script>

</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KSNRX24"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <nav class="navigation">
        <ul>
            <li><a href="#top">Top of Page</a></li>
            <li><a href="#faq">FAQ</a></li>
            <li><a href="#about-project">About Us</a></li>
            <li><a href="https://ourworldindata.org/coronavirus">Sources</a></li>
            <li id=last-updated-field>Last Updated: pending</li>
        </ul>
    </nav>
    <main id="top">
        {% block body_block %}

        {% endblock %}
    </main>

    <script>
    fetch("{% url 'dashboard:get_last_update' %}", {
        method: 'GET',
        mode: 'same-origin',
        cache: 'default',
    }).then((response) => {
        if (response.ok) {
            response.text().then((update) => {
                document.getElementById('last-updated-field').innerText = "Last Update: " + update;
            });
        } else {
            document.getElementById('last-updated-field').innerText = "Last Update: Failed to get date.";
        }
    });
    </script>

 <footer>
    <div class="footer-wrapper">
        <div id="about-project">
            <h4>About the project</h4>
            <p>This is a project created by team CS21 at University of Glasgow, in collaboration with Walt 
                Adamson, researcher at Institute of Biodiversity, Animal Health & Comparative Medicine.
            <br /><br />
            This website aims to give accurate COVID-19 data for Africa. All the data used 
            in the visualisations is gathered from Our World in Data.</p>
        </div>

        <div id="contact-info">
            <h4>Get in Touch</h4>
            <p>Have any feedback on the website? Or questions about it? Reach out!</p>
            <h6>Walt Adamson</h6>
            <ul class="contact-details">
                <li>Researcher at University of Glasgow</li>
                <li>Email: walt.adamson@glasgow.ac.uk</li>
                <!--Add more details here-->
            </ul>
        </div>
        <div id="faq">
            <h4>FAQs (Coming soon)</h4>
            <div class="alert alert-secondary">
                FAQ 1 - *FAQ HERE*
            </div>
            <div class="alert alert-secondary">
                FAQ 2 - *FAQ HERE*
            </div>
            <div class="alert alert-secondary">
                FAQ 3 - *FAQ HERE*
            </div>
        </div> 
    </div>
</footer>
</body>
</html>

covid_dashboard/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
    COVID-19 Africa Dashboard
{% endblock %}

{% block body_block %}

<div id="interactive-map" class="graph-wrapper">
    <div class="graph-head">Weekly Increase by African Country (statistics per 100k)</div>
    <div class="graph-body">
        <article id="choropleth" class="graph"></article>
    </div>
    <div class="description"><p>Hover over a country to see data.<br>
    Disclaimer: Country's and their borders are preset and not related to our political beliefs.</p></div>
</div>

<div id="top-increases" class="weekly-update-container">
    <div class="box">
      <div class="box-head">Largest Case Increase This Week</div>
      <div class="box-body">
          <table id="case-table" class="weekly-table">

          </table>
      </div>
    </div>
    <div class="box">
      <div class="box-head">Most Vaccinations Given This Week</div>
      <div class="box-body">
        <table id="vacc-table" class="weekly-table">

        </table>
      </div>
    </div>
    <div class="box">
      <div class="box-head">Most Deaths This Week</div>
      <div class="box-body">
        <table id="death-table" class="weekly-table">

        </table>
      </div>
    </div>
</div>

<div id="data-table" class="table-wrapper">
    <div class="table-head">Summary Table (per 100k)</div>
    <div class="table-body">
        <table id="all-countries-table" class="table table-striped"></table>
    </div>
    <div class="description"><p>Table can be sorted by column or you can search to find 
        data for a specifc country.</p></div>
</div>

<div id="cases-linegraph" class="graph-wrapper">
    <div class="graph-head">Average Number of New Cases per Week (per 100k)</div>
    <div class="graph-body">
        <article id="average-cases" class="graph"></article>
    </div>
    <div class="description"><p>Hover over lines to display data values. Click country name to add 
        or remove it from the graph. Double click a country name to remove all other countries 
        from graph. Double click inactive country name to bring all countries back to the graph.</p></div>
</div>

<div id="vaccination-coverage" class="graph-wrapper">
    <div class="graph-head">Vaccination Coverage by Country (as percentage of population)</div>
    <div class="graph-body">
        <article id="countries-vaccinations" class="graph"></article>
    </div>
    <div class="description"><p>Hover over bars to display data values. Click country name to add 
        or remove it from the graph. Double click a country name to remove all other countries 
        from graph. Double click inactive country name to bring all countries back to the graph.</p></div>
</div>

<div id="weekly-vaccines" class="graph-wrapper">
    <div class="graph-head">Number of New Vaccinations per Week (per 100k)</div>
    <div class="graph-body">
        <div class="dropdown-button">
            Use drop-down menu to view a country's administered vaccinations:
            <select class="countryChoice"></select>
        </div>
        <article id="country-new-vaccinations" class="graph"></article>
    </div>
    <div class="description"><p>Select a country to view using the drop-down box. Hover over bars to 
        display data values.</p></div>
</div>

<div id="weekly-deaths" class="graph-wrapper">
    <div class="graph-head">Number of New Deaths per Week (per 100k)</div>
    <div class="graph-body">
        <div class="dropdown-button">
            Use drop-down menu to view a country's reported deaths:
            <select class="countryChoice"></select>
        </div>
        <article id="country-new-deaths" class="graph"></article>
    </div>
    <div class="description"><p>Select a country to view using the drop-down box. Hover over bars to 
        display the data values.</p></div>
</div>

<script>
let mapRequest = new Request("{% url 'dashboard:get_map_data' %}");
const request_mapData = fetch(mapRequest, {
        method: 'GET',
        mode: 'same-origin',
        cache: 'default'
    }).then((response) => {
        if (response.ok) {
            response.json().then((content) => {
                draw_map(content);
            });
        } else {
            console.log("Failed to retrieve COVID-19 data.");
        }
    }
);

let summarydataRequest = new Request('{% url 'dashboard:get_summary_data' %}');
const summaryRequest = fetch(summarydataRequest, {
        method: 'GET',
        mode: 'same-origin',
        cache: 'default'
    }).then((response) => {
        if (response.ok) {
            response.json().then((content) => {
                create_summary_table(content);
            });
        } else {
            console.log("Failed to retrieve COVID-19 data.");
        }
    }
);

let weeklyMaxRequest = new Request('{% url 'dashboard:get_weekly_maxs' %}');
const request_weeklyMax = fetch(weeklyMaxRequest, {
        method: 'GET',
        mode: 'same-origin',
        cache: 'default'
    }).then((response) => {
        if (response.ok) {
            response.json().then((content) => {
                insert_weekly_maxs(content);
            });
        } else {
            console.log("Failed to retrieve COVID-19 data.");
        }
    }
);

let weeklyCasesRequest = new Request('{% url 'dashboard:get_covid_data' %}');
const request_weeklyCases = fetch(weeklyCasesRequest, {
        method: 'GET',
        mode: 'same-origin',
        cache: 'default'
    }).then((response) => {
        if (response.ok) {
            response.json().then((content) => {
                draw_average_cases(content);
            });
        } else {
            console.log("Failed to retrieve COVID-19 data.");
        }
    }
);

let vaccineDataRequest = new Request("{% url 'dashboard:get_vaccinated_percentage' %}");
const vaccine_request = fetch(vaccineDataRequest, {
        method: 'GET',
        mode: 'same-origin',
        cache: 'default'
    }).then((response) => {
        if (response.ok) {
            response.json().then((content) => {
                draw_countries_vaccinations(content);
            });
        } else {
            console.log("Failed to retrieve COVID-19 data.");
        }
    }
);

let weeklyVaccinationDataRequest = new Request("{% url 'dashboard:get_new_vaccinated_data' %}");
const weekly_vaccine_request = fetch(weeklyVaccinationDataRequest, {
        method: 'GET',
        mode: 'same-origin',
        cache: 'default'
    }).then((response) => {
        if (response.ok) {
            response.json().then((content) => {
                draw_country_new_vaccinations(content);
            });
        } else {
            console.log("Failed to retrieve COVID-19 data.");
        }
    }
);

let weeklyDeathsDataRequest = new Request("{% url 'dashboard:get_new_deaths_data' %}");
const weekly_deaths_request = fetch(weeklyDeathsDataRequest, {
        method: 'GET',
        mode: 'same-origin',
        cache: 'default'
    }).then((response) => {
        if (response.ok) {
            response.json().then((content) => {
                draw_country_new_deaths(content);
            });
        } else {
            console.log("Failed to retrieve COVID-19 data.");
        }
    }
);
</script>

{% endblock %}